overhaul hebits search plugin
Flexget/Flexget pull request #3367
Opened 2022-02-20 18:25 UTC by DirectorX

### Motivation for changes:

recently hebits had transition to gazelle based site

### Config usage if relevant (new plugin or updated schema):
```yaml
  trakt-movies-search:
    template:
      - global
      - movie
    priority: 10 # run after the movie queue fill task
    discover:
      what:
        - movie_list: movies
      from:
        - hebits:
            userid: 1337
            session: "1CIecR845NxF8qmahs6sS4oGTbSP5USmHYiL8U3uaD108zL2RW7R4LIngCbqdCRG"
            category: movies

      interval: 1 hour
    tmdb_lookup: yes
    list_match:
      from:
        - movie_list: movies
```

2022-02-21 18:21 UTC, paranoidi commented on flexget/components/sites/sites/hebits.py
> +    ```yaml
These are only visible from commandline help. You can't use formatting and should keep it short (no complete examples with other plugins).

2022-02-21 18:22 UTC, paranoidi requested changes
Please fix docstring, looks good otherwise :)

2022-02-23 08:10 UTC, DirectorX commented
ping @paranoidi

2022-03-26 21:18 UTC, DirectorX commented
ping @paranoidi

2022-03-27 15:54 UTC, merged

2022-03-27 15:54 UTC, gazpachoking commented
Thanks!