Pushsafer Notification Service
Flexget/Flexget pull request #3718
Opened 2023-03-15 21:03 UTC by appzer

### Motivation for changes:
- add missing Pushsafer parameter

### Detailed changes:
- add following API parameter to customize a push notification (Priority, Retry, Expire, Conform, Answer, AnswerOptions, AnswerForce)

2023-03-15 21:04 UTC, appzer commented
How to edit the documentation > https://flexget.com/Plugins/Notifiers/pushsafer

2023-03-16 20:16 UTC, gazpachoking requested changes

2023-03-16 20:16 UTC, gazpachoking commented on flexget/plugins/notifiers/pushsafer.py
What's the deal with this file? Accidentally added?

2023-03-17 16:24 UTC, gazpachoking commented
Thanks, looks good to me!

> How to edit the documentation > https://flexget.com/Plugins/Notifiers/pushsafer

You should be able to log in to the wiki with your github account, then edit the page yourself.
![image](https://user-images.githubusercontent.com/187133/225962230-a3756cef-885d-48b3-873f-f25bdb18e621.png)

2023-03-17 16:25 UTC, merged